# Generated by Django 5.1.6 on 2025-03-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderrightapp', '0005_alter_laptops_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Laptops',
        ),
    ]
