# Generated by Django 5.1.6 on 2025-03-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderrightapp', '0007_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
    ]
