# Generated by Django 5.1.6 on 2025-03-25 07:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderrightapp', '0008_remove_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
