# Generated by Django 5.1.6 on 2025-03-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderrightapp', '0010_newarrivals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BestSellers',
        ),
    ]
