# Generated by Django 5.1.6 on 2025-03-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderrightapp', '0012_bestsellers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url', models.TextField(blank=True, null=True)),
                ('paragraph1', models.TextField(blank=True, null=True)),
                ('paragraph2', models.TextField(blank=True, max_length=100000, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date')),
            ],
        ),
    ]
