# Generated by Django 5.1.6 on 2025-03-27 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderrightapp', '0013_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='paragraph1',
            new_name='paragraph',
        ),
        migrations.RemoveField(
            model_name='post',
            name='paragraph2',
        ),
    ]
